### PR TITLE
Corbett/update tpls

### PR DESCRIPTION
**Pull request by corbett5**

### CODE REVIEW

**Review by rrsettgast — APPROVED** [review]
Why the change of case for raja?

**Comment by corbett5** [comment]
@rrsettgast  
> 
> Why the change of case for raja?

So we can just do `find_package(RAJA)` instead of all the complicated logic that was in `FindRAJA.cmake`.

**Comment by corbett5** [comment]
@af1990 
> 
> I cannot run on Lassen, so I cannot check that the changes in the lassen host-config are working.
> The renaming of RAJA is fine.

The lassen issues don't appear to be due to the TPL update.

**Comment by corbett5** [comment]
Changes already added.

**Pull request closed without merging**
